overwrite: true
schema: tmp/graphql_introspection.json
config:
  vueCompositionApiImportFrom: vue
generates:
  ./app/frontend/common/graphql/types.ts:
    plugins:
      - typescript
  ./app/frontend/common/graphql/api.ts:
    documents: 'app/frontend/common/graphql/**/*.graphql'
    preset: import-types
    presetConfig:
      typesPath: './types'
    plugins:
      - typescript-operations
      - typescript-vue-apollo
  ./app/frontend/apps/mobile/graphql/api.ts:
    documents: 'app/frontend/apps/mobile/graphql/**/*.graphql'
    preset: import-types
    presetConfig:
      typesPath: '@common/graphql/types'
    plugins:
      - typescript-operations
      - typescript-vue-apollo
