overwrite: true
schema: tmp/graphql_introspection.json
documents: 'app/frontend/apps/mobile/graphql/**/*.graphql'
generates:
  ./app/frontend/apps/mobile/graphql/api.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
    config:
      vueCompositionApiImportFrom: vue
  ./app/frontend/apps/mobile/graphql/schema.json:
    plugins:
      - 'introspection'
