browser:build:
  stage: test
  extends:
    - .tags_docker
    - .services_postgresql
  artifacts:
    expire_in: 1 week
    paths:
    - public/assets/.sprockets-manifest*
    - public/assets/application-*
    - public/assets/knowledge_base*
    - public/assets/print-*
    - public/vite
  variables:
    RAILS_ENV: "production"
  script:
    - bundle exec rake zammad:db:unseeded
    - VITE_TEST_MODE=1 bundle exec rake assets:precompile
